---
title: "Práctica 2"
author: "Suriel Quevedo Ortiz"
date: '2022-03-07'
output:
  html_document:
    toc: yes
    toc_depth: 3
    toc_float:
      smooth_scrool: no
    number_sections: yes
    theme: united
    highlight: tango
---

# Funciones de ayuda

```{r}
# Muestra la ayuda de la media aritmética
#help (mean)

# Otra forma de ejecutar la ayuda de una función
#?mean

# Se utiliza para obtener la ayuda de alguna función
# de la cual desconocemos el nombre exacto
#help.search("median")
```

# Creación de variables

```{r}
# Creamos una variable de tipo double utilizando el operador
# "<-" para asignar el valor
doub <- 4

# Creamos una variable utilizando el operador "=" para asignar el valor
doub=4

# Muestra el valor de la variable doub
doub

# Creamos variable tipo integer
int=as.integer(4)
int

# Variable lógica
logi=FALSE
logi

# Variable tipo cadena de caracteres
char1="Hola"
char1
char2 <- "5 + 6"
char2
```

# Comprobación del tipo de una variable

```{r}
typeof(doub)
typeof(int)
typeof(char1)
```

# Operadores básicos

```{r}
2^3 # Elevación
9/6 # Multiplicación
9%%6# Módulo
```

## Operadores de asignación

```{r}
a=2+2 # resultado de 2+2 se asigna a la variable a
b=3*2 # resultado de 3*2 se asigna a la variable b
b-a -> c # resultado de b-a se asigna a la variable c
a
b
c
```

## Operadores comparativos

```{r}
a == 5
a==4 & b<2
a==4 | b<2
a==4 | b<2 & c!=9
```

# Otras funciones interesantes

```{r}
x <- 9
sqrt(x) #Raíz cuadrada de x
x <- -9
abs(x) #Valor absoluto de x
x <- pi/2
sin(x) #Seno de x
x <- pi
cos(x) #Coseno de x
x <- 0
tan(x) #Tangente de x
x <- pi
log(x) #Logaritmo neperiano de x
log10(x) #Logaritmo decimal de x
x <- 2
exp(x) #Exponencial de x
```

# Estructuras de datos

## Vectores

```{r}
vec=c(1,3,14)
vec
```

## Matrices

```{r}
mat1 <- matrix(c(1,2,3,4,5,6), nrow = 2, ncol = 3) #por defecto las matrices se completan por columna
mat1
mat2 <- matrix(c(1,2,3,4,5,6), nrow = 2, ncol = 3, byrow = TRUE) #byrow=TRUE indica que complete la matriz por filas
mat2
m <- matrix(c(1,1,2,1),2,2)
m
```

## Array
```{r}
arr <- array(c(1,2,3,4,5,6,7,8), dim = c(2,2,2)) #el último 2 indica que son dos matrices
arr
```

## Factores ordenados

```{r}
ord <- ordered(c(1,2,1,2,3,1,2,1,2), levels = c(1,2,3))
ord
ord2 <- ordered(c(1,2,1,2,3,1,2,1,2), levels = c(2,3,1))
ord2
ord3 <- ordered(c(1,2,1,2,3,1,2,1,2), levels = c(3,1,2))
ord3
```

## Factores no ordenados

```{r}
fac <- factor(c("H","M","M","H","H","M"), levels = c("H","M"))
fac
fac2 <- factor(c("H","M","M","H","H","M"), levels = c("M","H"))
fac2
```

## Data frames y listas

```{r}
a <- c(1,5,4)
b <- c("Hola","adiós","hasta luego")
c <- c(TRUE,FALSE,FALSE)
d <-c(1,2,3,4,5)
dataframe <- data.frame(a,b,c)
dataframe
list1 <- list(a,b,c)
list1
list2 <- list(a,b,c,d)
list2
```

## Acceso a los elementos de las estructuras de datos

```{r}
vec[3]
mat1[2,3]
arr[2,1,2] #el elemento de la segunda fila, primera columna de la segunda matriz
#También se puede acceder a varios elementos usando la función de concatenación c
mat1[c(1,2),3] #los elementos (1,3) y (2,3) de la matriz
mat1[1,] #accediendo a una fila completa
mat1[,c(1,2)] #accediendo a una columna completa
#Accediendo a los elementos de un factor ordenado y no ordenado
fac[2]
ord[c(2,5)]
#En los data frames se utiliza el símbolo $ seguido del nombre de la columna dentro del dataframe
dataframe$a
#Y una vez obtenida la columna, es posible obtener los valores usando los corchetes
dataframe$a[1]
#Alternativamente, un data frame puede verse como una matriz, por tanto, pueden usarse corchetes para acceder a sus elementos
dataframe[1,]
#Y para acceder a un elemento dentro de una lista, se utilizan corchetes dobles
list1[[2]]
list2[[4]][2]
```

# Ejemplos

```{r}
peso <- c(19,14,15,17,20,23,30,19,25)
peso < 20
peso<20 | peso>25
peso[peso<20]
peso[peso<20 & peso!=15]
```