---
title: "Práctica 10"
author: "Suriel Quevedo Ortiz"
date: '2022-03-28'
output:
  html_document:
    toc: yes
    toc_depth: 3
    toc_float:
      smooth_scrool: no
    number_sections: yes
    theme: united
    highlight: tango
---

```{r setup, include=FALSE}
library(tidyverse)
library(dplyr)
data <- read.csv("mexico_covid19.csv", header = TRUE)
```

# a) Primeros 6 registros

```{r}
head(data,6)
```

# b) Dimensiones de la base de datos y tamaño del archivo

```{r}
dim(data)
object.size(data)
```

# c) Cambiar variable sexo a variable categórica

```{r}
str(data$SEXO)
data$SEXO <- as.character(data$SEXO)
data <- mutate(data, SEXO = ifelse(SEXO == 1, "MUJER",
                                   ifelse(SEXO == 2, "HOMBRE","NO_ESPECIFICADO")))
str(data$SEXO)
```

# d) Resumen

```{r}
fe<-select(data,ENTIDAD,RESULTADO,SEXO)
fe$ENTIDAD<-as.character(fe$ENTIDAD)
fe<-group_by(fe,SEXO)

res<-table(fe$ENTIDAD,fe$RESULTADO,fe$SEXO)                   
res
```

# e) Gráfica

```{r}
barplot(margin.table(res,1),
        main = "Casos por entidad",
        xlab = "Entidades", ylab = "Número de caso", horiz = FALSE,
        col = "blue")
```

# f) Modificar la variable sector

```{r}
str(data$SECTOR)
data$SECTOR<-as.character(data$SECTOR)
data <- mutate(data, SECTOR = ifelse(SECTOR == 1, "CRUZ_ROJA",
                                   ifelse(SECTOR == 2, "DIF",
                                          ifelse(SECTOR == 3, "ESTATAL",
                                                 ifelse(SECTOR == 4, "IMSS",
                                                        ifelse(SECTOR == 5, "IMSS_BIENESTAR",
                                                               ifelse(SECTOR == 6, "ISSTE",
                                                                      ifelse(SECTOR == 7, "MUNICIPAL",
                                                                             ifelse(SECTOR == 8, "PEMEX",
                                                                                    ifelse(SECTOR == 9, "PRIVADA",
                                                                                           ifelse(SECTOR == 10, "SEDENA",
                                                                                                  ifelse(SECTOR == 11, "SEMAR",
                                                                                                         ifelse(SECTOR == 12, "SSA",
                                                                                                                ifelse(SECTOR == 13, "UNIVERSITARIO","NO_ESPECIFICADO"))))))))))))))
str(data$SECTOR)
```

# g) Gráfico

```{r}
oax <- select(data, SECTOR,RESULTADO)
oax <- as.data.frame(table(oax$SECTOR,oax$RESULTADO))
oax
ggplot(data = oax)+
  aes(x=Var1, y = Freq) + 
  geom_bar(stat="identity")
```

# h) Filtrar casos positivos de oaxaca

```{r}
oax <- select(data,ENTIDAD,RESULTADO,OBESIDAD,ASMA,HIPERTENSION,RENAL_CRONICA)
oax$ENTIDAD <- as.character(oax$ENTIDAD)
oax_pos <- filter(oax,
                ENTIDAD =="Oaxaca"&
                RESULTADO == 1)
table(oax_pos$OBESIDAD)
table(oax_pos$ASMA)
table(oax_pos$HIPERTENSION)
table(oax_pos$RENAL_CRONICA)
```

# i) Edades de casos positivos

```{r}
oax <- select(data,ENTIDAD,RESULTADO,EDAD)
oax$ENTIDAD <- as.character(oax$ENTIDAD)
oax_pos <- filter(oax,
                ENTIDAD =="Oaxaca"&
                RESULTADO == 1)
#oax_pos
boxplot(oax_pos$EDAD)
```